src/Entity/Teacher.php
<?php

namespace App\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="App\Repository\TeacherRepository")
 */
class Teacher {

    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="smallint", nullable=true)
     */
    private $level;

    /**
     * @ORM\Column(type="string", length=25, nullable=true)
     */
    private $firstname;

    /**
     * @ORM\Column(type="string", length=25, nullable=true)
     */
    private $lastname;

    /**
     * @ORM\Column(type="string", length=25, nullable=true)
     */
    private $patronym;

    /**
     * @ORM\Column(type="smallint", nullable=true, options={"default": 0})
     */
    private $type;

    /**
     * @ORM\Column(type="smallint", nullable=true, options={"default": 0})
     */
    private $degree;

    /**
     * @ORM\Column(type="integer", nullable=true, options={"default": 0})
     */
    private $systemId;

    /**
     * @ORM\Column(type="smallint", options={"default": 1})
     */
    private $status;

    /**
     * @ORM\Column(type="datetime", nullable=true)
     */
    private $dateUpdated;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\Group", mappedBy="advisor")
     * @ORM\OrderBy({"lastname" = "ASC"})
     */
    private $advisedGroups;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\Department", inversedBy="teachers")
     * @ORM\OrderBy({"lastname" = "ASC"})
     * @ORM\JoinColumn(nullable=false)
     */
    private $department;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\TaughtCourse", mappedBy="teacher")
     */
    private $taughtCourses;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\StudentAbsence", mappedBy="author")
     */
    private $studentAbsences;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\ScheduleItem", mappedBy="teacher")
     */
    private $scheduleItems;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\TeacherAttendance", mappedBy="teacher")
     */
    private $teacherAttendances;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\TeacherWorkItem", mappedBy="teacher")
     * @ORM\OrderBy({"viewOrder" = "ASC"})
     */
    private $teacherWorkItems;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\ReportedWork", mappedBy="teacher")
     * @ORM\OrderBy({"lastname" = "ASC"})
     */
    private $reportedWorks;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\TeacherWorkSet", mappedBy="teacher")
     */
    private $teacherWorkSets;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\HostelRoom", mappedBy="instructor")
     */
    private $hostelRooms;

    /**
     * @ORM\Column(type="string", length=100, nullable=true)
     */
    private $scheduleName;

    public function __construct() {
        $this->advisedGroups = new ArrayCollection();
        $this->taughtCourses = new ArrayCollection();
        $this->studentAbsences = new ArrayCollection();
        $this->scheduleItems = new ArrayCollection();
        $this->teacherAttendances = new ArrayCollection();
        $this->teacherWorkItems = new ArrayCollection();
        $this->reportedWorks = new ArrayCollection();
        $this->teacherWorkSets = new ArrayCollection();
        $this->hostelRooms = new ArrayCollection();
    }

    public function getId(): ?int {
        return $this->id;
    }

    public function getLevel(): ?int {
        return $this->level;
    }

    public function setLevel(?int $level): self {
        $this->level = $level;

        return $this;
    }

    public function getFirstname(): ?string {
        return $this->firstname;
    }

    public function setFirstname(?string $firstname): self {
        $this->firstname = $firstname;

        return $this;
    }

    public function getLastname(): ?string {
        return $this->lastname;
    }

    public function setLastname(?string $lastname): self {
        $this->lastname = $lastname;

        return $this;
    }

    public function getPatronym(): ?string {
        return $this->patronym;
    }

    public function setPatronym(?string $patronym): self {
        $this->patronym = $patronym;

        return $this;
    }

    public function getType(): ?int {
        return $this->type;
    }

    public function setType(?int $type): self {
        $this->type = $type;

        return $this;
    }

    public function getFullname(): ?string {
        return $this->lastname . " " . $this->firstname;
    }

    public function getThreeNames(): ?string {
        return $this->lastname . " " . $this->firstname . " " . $this->patronym;
    }

    public function getShortFullname(): ?string {
        return mb_substr($this->firstname, 0, 1) . "." . $this->lastname;
    }

    public function getInitials(): ?string {
        return mb_substr($this->firstname, 0, 1) . "." . mb_substr($this->lastname, 0, 1);
    }

    public function getDegree(): ?int {
        return $this->degree;
    }

    public function setDegree(?int $degree): self {
        $this->degree = $degree;

        return $this;
    }

    public function getSystemId(): ?int {
        return $this->systemId;
    }

    public function setSystemId(?int $systemId): self {
        $this->systemId = $systemId;

        return $this;
    }

    public function getStatus(): ?int {
        return $this->status;
    }

    public function setStatus(int $status): self {
        $this->status = $status;

        return $this;
    }

    public function getDateUpdated(): ?\DateTimeInterface {
        return $this->dateUpdated;
    }

    public function setDateUpdated(?\DateTimeInterface $dateUpdated): self {
        $this->dateUpdated = $dateUpdated;

        return $this;
    }

    /**
     * @return Collection|Group[]
     */
    public function getAdvisedGroups(): Collection {
        return $this->advisedGroups;
    }

    public function addAdvisedGroup(Group $advisedGroup): self {
        if (!$this->advisedGroups->contains($advisedGroup)) {
            $this->advisedGroups[] = $advisedGroup;
            $advisedGroup->setAdvisor($this);
        }

        return $this;
    }

    public function removeAdvisedGroup(Group $advisedGroup): self {
        if ($this->advisedGroups->contains($advisedGroup)) {
            $this->advisedGroups->removeElement($advisedGroup);
            // set the owning side to null (unless already changed)
            if ($advisedGroup->getAdvisor() === $this) {
                $advisedGroup->setAdvisor(null);
            }
        }

        return $this;
    }

    public function getDepartment(): ?Department {
        return $this->department;
    }

    public function setDepartment(?Department $department): self {
        $this->department = $department;

        return $this;
    }

    public function getFaculty(): ?Faculty {
        return $this->getDepartment()->getFaculty();
    }

    public function isDean(Teacher $teacher) {
        $deans = $this->getFaculty()->getAllDeans();
        if (in_array($teacher, $deans)) {
            return true;
        } else {
            return false;
        }
    }

    public function isDepartmentHead(Teacher $teacher) {
        return ($teacher == $this->getDepartment()->getDepartmentHead());
    }

    /**
     * @return Collection|TaughtCourse[]
     */
    public function getTaughtCourses(): Collection {
        return $this->taughtCourses;
    }

    public function addTaughtCourse(TaughtCourse $taughtCourse): self {
        if (!$this->taughtCourses->contains($taughtCourse)) {
            $this->taughtCourses[] = $taughtCourse;
            $taughtCourse->setTeacher($this);
        }

        return $this;
    }

    public function removeTaughtCourse(TaughtCourse $taughtCourse): self {
        if ($this->taughtCourses->contains($taughtCourse)) {
            $this->taughtCourses->removeElement($taughtCourse);
            // set the owning side to null (unless already changed)
            if ($taughtCourse->getTeacher() === $this) {
                $taughtCourse->setTeacher(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection|StudentAbsence[]
     */
    public function getStudentAbsences(): Collection {
        return $this->studentAbsences;
    }

    public function addStudentAbsence(StudentAbsence $studentAbsence): self {
        if (!$this->studentAbsences->contains($studentAbsence)) {
            $this->studentAbsences[] = $studentAbsence;
            $studentAbsence->setAuthor($this);
        }

        return $this;
    }

    public function removeStudentAbsence(StudentAbsence $studentAbsence): self {
        if ($this->studentAbsences->contains($studentAbsence)) {
            $this->studentAbsences->removeElement($studentAbsence);
            // set the owning side to null (unless already changed)
            if ($studentAbsence->getAuthor() === $this) {
                $studentAbsence->setAuthor(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection|ScheduleItem[]
     */
    public function getScheduleItems(): Collection {
        return $this->scheduleItems;
    }

    public function addScheduleItem(ScheduleItem $scheduleItem): self {
        if (!$this->scheduleItems->contains($scheduleItem)) {
            $this->scheduleItems[] = $scheduleItem;
            $scheduleItem->setTeacher($this);
        }

        return $this;
    }

    public function removeScheduleItem(ScheduleItem $scheduleItem): self {
        if ($this->scheduleItems->contains($scheduleItem)) {
            $this->scheduleItems->removeElement($scheduleItem);
            // set the owning side to null (unless already changed)
            if ($scheduleItem->getTeacher() === $this) {
                $scheduleItem->setTeacher(null);
            }
        }

        return $this;
    }

    /**

templates/taught_course/form.html.twig
{% extends 'main.html.twig' %}

{% block moduletitle %}Taught Course Form{% endblock %}
{% block main %}
    <div style="width:90%;margin:auto;"><h3>Taught Course Form</h3></div>
    <div style="width:90%;margin:auto;">
        {% form_theme form 'bootstrap_4_horizontal_layout.html.twig' %}
        {{ form_start(form) }}
        {{ form_widget(form) }}
        <button type="submit" class="btn btn-primary">Create / Update</button>
        {{ form_end(form) }}
    </div>
{% endblock %}
{% block customjs %}
    <script>
        jQuery(document).ready(function () {
            populate_items($('#taught_course_form_student_groups').val());
            autocompleting();
        });
        var items = Array();
        function autocompleting()
        {
            $("#taught_course_form_student_groups_select").autocomplete({
                minLength: 3,
                source: function (request, response) {
                    $.ajax({
                        url: "/faculty/group/jsonlist/" + request.term,
                        dataType: "json",
                        success: function (data) {
                            response(data);
                        }
                    });
                },
                focus: function (event, ui) {
                    //$( "#taught_course_form_student_groups_select" ).val( ui.item.value );
                    return false;
                },
                select: function (event, ui) {
                    add_item(ui.item.id, ui.item.value);

                    return false;
                }
            })
                    .autocomplete("instance")._renderItem = function (ul, item) {
                return $("<li>")
                        .append("<div style='50px; margin-top:5px;'>" + item.value + "</div>")
                        .appendTo(ul);
            };
        }

        function add_item(id, name)
        {
            items.push([id, name]);
            refresh_items();
        }

        function remove_item(index)
        {
            items.splice(index, 1);
            refresh_items();
        }

        function refresh_items()
        {
            var str = '';
            var ids = Array();
            for (i = 0; i < items.length; i++)
            {
                str += "<div style='50px; margin-top:5px;'>" + items[i][1] + " <button onclick='remove_item(" + i + ");'>remove</button></div>";
                ids.push(items[i][0]);
            }
            $('#items_list').html(str);
            $("#taught_course_form_student_groups").val(ids.join());
            $("#taught_course_form_student_groups_select").val('');
        }

        function populate_items(ids)
        {
            var str = '';
            items = Array();
            //console.log(ids);
            $.ajax({
                url: "/faculty/group/jsonlist/items/" + ids,
                type: 'GET',
                dataType: 'json',
                success: function (data) {
                    //console.log(data);
                    //var json = JSON.parse(data.responseText);
                    $.each(data, function (i, item) {
                        //console.log(data[i].student_lastname + ' ' + data[i].student_firstname + ' ' + data[i].student_patronym);
                        add_item(data[i].id, data[i].value);
                        refresh_items();
                    });
                },
                error: function (data) {}
            });

        }
    </script>
{% endblock %}{# empty Twig template #}

templates/taught_course/report.html.twig
{% extends 'main.html.twig' %}
{% block customcss %}
    <style>
        .extrasmall {font-size:10px;}
        .small {font-size:12px;}
        .today_class {background-color:green;color:#fff;}
        .everyday_class {}
        .bold {font-weight:bold;}
    </style>
{% endblock %}
{% block moduletitle %}Courses{% endblock %}
{% block main %}
    <h4>{{ report_title }}</h4>
    {% if faculty is not null %}
        <h6><span class='bold'>Faculty:</span> {{ faculty.nameEnglish }}</h6>
    {% endif %}
    {% if department is not null %}
        <h6><span class='bold'>Department: </span> {{ department.nameEnglish }}</h6>
    {% endif %}
    {% if teacher is not null %}
        <h6><span class='bold'>Teacher: </span> {{ teacher.fullname }}</h6>
    {% endif %}
    <table class="table table-bordered table-sm table-striped small" id="mainTable">
        <thead>
            <tr>
                <th>#</th>
                <th>Semester</th>
                <th>Course</th>
                <th>Instructor</th>
                <th>Department</th>
                <th>Group</th>
                <th>Links</th>
            </tr>
        </thead>
        <tbody>
            {% for course in courses %} 
                <tr>
                    <td>{{ loop.index }}</td>
                    <td>{{ course.semester }}</td>
                    <td>{{ course.nameEnglish }}</td>
                    <td>{{ course.teacher.fullname }}</td>
                    <td>{{ course.department.letterCode }}</td>
                    <td>{{ course.studentGroups }}</td>
                    <td>
                        <a href='/interop/exporter/courseattendancesheet/{{ course.id }}/0/{{ course.semester-1 }}'>Midterm Attendance Sheet</a>
                        | <a href='/interop/exporter/courseattendancesheet/{{ course.id }}/1/{{ course.semester-1 }}'>Final Attendance</a>
                        | <a href='/interop/exporter/courseattendancesheet/{{ course.id }}/2/{{ course.semester-1 }}'>SIW Attendence </a>
                        | <a href='/interop/exporter/courseattendancesheet/{{ course.id }}/3/{{ course.semester-1 }}'>Make up Attendance</a>
                        <br>
                        <a href='/interop/exporter/courseexamcover/{{ course.id }}/0/{{ course.semester-1 }}'>Midterm exam cover</a>
                        | <a href='/interop/exporter/courseexamcover/{{ course.id }}/1/{{ course.semester-1 }}'>Final exam cover</a>
                        | <a href='/interop/exporter/courseexamcover/{{ course.id }}/2/{{ course.semester-1 }}'>SIW exam cover</a>
                        | <a href='/interop/exporter/courseexamcover/{{ course.id }}/3/{{ course.semester-1 }}'>Make up Final exam cover</a>
                        <br>
                        {% if course.gradingType==1 %}
                            <a href='/interop/exporter/coursegradesheet/{{ course.id }}/0/{{ course.semester-1 }}'>Exam Grade Sheet</a>
                            | <a href='/grading/transcriptcourse/course/view/{{ course.id }}/{{ course.courseCode }}/{{ course.studentGroups }}/{{ course.year }}'>Grades</a>
                        {% endif %}
                    </td>
                </tr>
            {% endfor %}
        </tbody>
    </table>
{% endblock %}
{% block customjs %}
    <script type="text/javascript">
        var selectedItems = Array();
        $(document).ready(function () {

            $("#begindatepicker").datepicker({dateFormat: "yy-mm-dd"});
            $("#enddatepicker").datepicker({dateFormat: "yy-mm-dd"});

            $('#btn_view_interval').click(function (e) {
                view_interval();
            });

            $('#btn_view_today').click(function (e) {
                view_today();
            });

            $('.absence-check').click(function (e) {
                //console.log($(this).data('absence').id);
                toggleSelect($(this));
            });

            $('.dropdown-item.present').click(function (e) {
                send_attendance($(this).attr('data-id'), 'present');
            });
            $('.dropdown-item.absent').click(function (e) {
                send_attendance($(this).attr('data-id'), 'absent');
            });
            $('.dropdown-item.note').click(function (e) {
                send_attendance($(this).attr('data-id'), 'note');
            });
            $('#btnCourse').click(function (e) {
                send_attendance($(this).attr('data-id'), 'teacher');
            });
            $('.dropdown-item.excuse').click(function (e) {
                send_attendance($(this).attr('data-id'), 'excuse');
                $('#absence_excusestatus').val(1);
            });
            $('.dropdown-item.unexcuse').click(function (e) {
                send_attendance($(this).attr('data-id'), 'unexcuse');
                $('#absence_excusestatus').val(0);
            });
            $('.dropdown-item.recoverteacher').click(function (e) {
                send_attendance($(this).attr('data-id'), 'recoverteacher');
            });
            $('.dropdown-item.recoverdean').click(function (e) {
                send_attendance($(this).attr('data-id'), 'recoverdean');
            });
            $('#mainTable').DataTable({
                dom: 'Bfrtip',
                lengthMenu: [
                    [10, 25, 50, -1],
                    ['10 rows', '25 rows', '50 rows', 'Show all']
                ],
                buttons: [
                    'pageLength', 'copy', 'excel', 'pdf'
                ]
            });
        });

        function toggleSelect(obj)
        {
            var id = obj.data('absence').id;
            if (obj.is(":checked"))
            {
                //add item
                selectedItems.push(id);

            } else
            {
                //remove item
                const index = selectedItems.indexOf(id);
                if (index > -1) {
                    selectedItems.splice(index, 1);
                }
            }
            //console.log(selectedItems); 
        }

        function downloadReferrals()
        {
            var ids = selectedItems.join(",");
            //console.log(ids);
            p = '/interop/exporter/referrals/' + ids;
            window.location.href = p;
        }

        function send_attendance(id, action)
        {
            //console.log(id);
            var absence = $("#data" + id).data("absence");
            //console.log(absence);

            absence_note_new = absence.note;
            absence_excusenote_new = absence.excusenote;
            absence_recovernote_new = absence.recovernote;
            if (action == "note")
            {
                $('#action').val('note');
                var absence_note_input = prompt("Please enter note", absence.note);
                absence_note_new = absence_note_input;
            }
            if (action == "excuse")
            {
                $('#action').val('excusenote');
                var absence_note_input = prompt("Please enter excuse note", absence.excusenote);
                absence_excusenote_new = absence_note_input;
            }
            if (action == "recoverdean")
            {
                $('#action').val('recovernote');
                var absence_note_input = prompt("Please enter recover note", absence.recovernote);
                absence_recovernote_new = absence_note_input;
            }

            $('#action').val(action);
            $('#div_id').val(id);
            $('#absence_id').val(absence.id);
            $('#student_id').val(absence.student_id);
            $('#course_id').val(absence.course_id);
            $('#teacher_id').val(absence.teacher_id);
            $('#absence_date').val(absence.date);
            $('#absence_session').val(absence.session);
            $('#absence_note').val(absence_note_new);
            $('#absence_excusenote').val(absence_excusenote_new);
            $('#absence_recovernote').val(absence_recovernote_new);
            $('#absence_status').val(absence.status);
            $('#absence_type').val(absence.type);

            send_data();
            if (action == 'present')
                $("#data" + id).html("<img src='/build/images/attendance_check_icon.png'>");
            else if (action == 'absent')
                $("#data" + id).html("<img src='/build/images/attendance_cross_icon.png'>");
        }

        function send_data()
        {
            p = '/faculty/attendance/process';
            var inputs = $("#mainform").serialize();
            console.log(inputs);
            //return;
            $.ajax({
                type: "POST",
                url: p,
                data: inputs,
                success: function (msg) {
                    //console.log(msg);
                    $("#info" + $('#div_id').val()).html(msg);
                }});
        }
    </script>
{% endblock %}